baseURL = 'https://sharonzhou.site/'
languageCode = 'zh-cn'
title = 'My Blog'
theme = 'PaperMod'

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params.author]
  name = "sharon"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowShareButtons = false
  comments = true

[params.homeInfoParams]
  Title = "Welcome"
  Content = "个人博客"

[[menus.main]]
  name = "文章"
  url = "/posts/"
  weight = 1

[[menus.main]]
  name = "归档"
  url = "/archives/"
  weight = 2

[[menus.main]]
  name = "搜索"
  url = "/search/"
  weight = 3

[[menus.main]]
  name = "关于"
  url = "/about/"
  weight = 4
